# Generated by Django 3.2.16 on 2023-03-17 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminlawyer', '0011_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Feedback',
        ),
    ]
