# Generated by Django 3.2.16 on 2023-03-17 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminlawyer', '0013_feedback'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='date',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='time',
        ),
    ]
