# Generated by Django 3.2.16 on 2023-03-24 02:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminlawyer', '0015_auto_20230323_2223'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Appointment',
        ),
    ]
