# Generated by Django 3.2.16 on 2023-03-28 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminlawyer', '0017_appointment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Appointment',
        ),
    ]
