# Generated by Django 3.2.16 on 2023-03-28 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminlawyer', '0020_auto_20230329_0117'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Feedback',
        ),
    ]
