# Generated by Django 3.2.16 on 2023-03-28 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminlawyer', '0031_alter_feedback_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Feedback',
        ),
    ]
