# Generated by Django 3.2.16 on 2023-03-28 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminlawyer', '0033_feedback'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Feedback',
        ),
    ]
