# Generated by Django 3.2.16 on 2023-04-02 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminlawyer', '0035_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='cases',
            name='remarks',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='cases',
            name='result',
            field=models.CharField(default='', max_length=5),
        ),
    ]
