# Generated by Django 3.2.16 on 2023-04-03 00:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminlawyer', '0036_auto_20230403_0440'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Feedback',
        ),
    ]
