# Generated by Django 3.2.16 on 2023-04-03 00:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminlawyer', '0038_feedback'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='user',
        ),
    ]
